name: Run Vercel Cron Job

on:
  schedule:
    - cron: "00 19 * * *"  # 12:30 AM IST
    - cron: "00 20 * * *"  # 1:30 AM IST
  workflow_dispatch:

concurrency:
  group: "vercel-cron-job"
  cancel-in-progress: true

jobs:
  trigger-vercel-api-1:
    if: github.event.schedule == '00 19 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API for First Job
        run: curl -X GET "https://expense-trackerr-server.vercel.app/api/cron"

  trigger-vercel-api-2:
    if: github.event.schedule == '00 20 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API for Second Job
        run: curl -X GET "https://expense-trackerr-server.vercel.app/api/cron-to-deduprecurring"
