name: Run Vercel Cron Job

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes
  workflow_dispatch: # Allows manual triggering from GitHub Actions UI

jobs:
  trigger-vercel-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API
        run: curl -X GET "https://expense-trackerr-server.vercel.app/api/cron"
