name: Run Vercel Cron Job

on:
  schedule:
    - cron: "30 18 * * *"  # Runs at 12:00 AM IST daily (6:30 PM UTC)
  workflow_dispatch:       # Allows manual trigger

concurrency:
  group: "vercel-cron-job"
  cancel-in-progress: true  # Ensures only one run at a time

jobs:
  trigger-vercel-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API
        run: curl -X GET "https://expense-trackerr-server.vercel.app/api/cron"
